name: Increase Azure File Share Quota

# This workflow is triggered by an external webhook from Azure Monitor
on:
  repository_dispatch:
    types: [increase-storage-quota]

jobs:
  increase-quota:
    runs-on: ubuntu-latest
    steps:
      - name: 'Az CLI Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Increase File Share Quota'
        shell: bash
        run: |
          # --- Configuration ---
          RESOURCE_GROUP="rg-container-app-storage-test-50"
          STORAGE_ACCOUNT_NAME="mycontainerapp123" # IMPORTANT: Replace with your storage account name
          FILE_SHARE_NAME="storage-automation"
          INCREMENT_GB=5 # How many GB to add each time
          MAX_QUOTA_GB=500 # A safety limit to prevent runaway costs

          echo "Fetching current quota for file share: $FILE_SHARE_NAME..."

          # Get current quota in GiB
          CURRENT_QUOTA_GB=$(az storage share show \
            --name $FILE_SHARE_NAME \
            --account-name $STORAGE_ACCOUNT_NAME \
            --resource-group $RESOURCE_GROUP \
            --query "quota" -o tsv)

          echo "Current quota is $CURRENT_QUOTA_GB GiB."

          if [[ -z "$CURRENT_QUOTA_GB" ]]; then
            echo "Error: Could not retrieve current quota. Exiting."
            exit 1
          fi

          # Calculate the new quota
          NEW_QUOTA_GB=$((CURRENT_QUOTA_GB + INCREMENT_GB))

          echo "New calculated quota is $NEW_QUOTA_GB GiB."

          # Safety check against the maximum quota
          if (( $(echo "$NEW_QUOTA_GB > $MAX_QUOTA_GB" | bc -l) )); then
            echo "Error: Calculated new quota ($NEW_QUOTA_GB GiB) exceeds the maximum allowed limit ($MAX_QUOTA_GB GiB). Manual intervention required."
            exit 1
          fi

          echo "Updating file share quota to $NEW_QUOTA_GB GiB..."

          # Update the quota
          az storage share update \
            --name $FILE_SHARE_NAME \
            --account-name $STORAGE_ACCOUNT_NAME \
            --resource-group $RESOURCE_GROUP \
            --quota $NEW_QUOTA_GB

          echo "Successfully updated file share quota for '$FILE_SHARE_NAME' to $NEW_QUOTA_GB GiB."
